apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: httpd_app_nautilus
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  namespace: devops-tools
  labels:
    app: httpd_app_nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      containers:
        - name: httpd-container-nautilus
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-data
            mountPath: /var/www/html
      volumes:
        - name: nginx-data
          hostPath:
            path: /nfs/devops/kubernetes/test