apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs
provisioner: example.com/external-nfs
parameters:
  server: vdc.idp.local
  path: /devops/
  readwrite: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain